### ISSUE TITLE
Error executing 

### ISSUE THREAD

**Issue by avelinoferreira** [IBM/zOS-BCPii#22]
Hi, seems to me an environmental error but I could not find any information or where to look. I have GDPS in place so BCPii configuration is not a problem here but using this rexx it gives me following error:

Rexx RC: (0)                         
HTTP Status: (500)                   
Reason Code: (4212)  

I really understand that this Rexx is provided "AS IS" but if you have any tip on how to check the errors, I would appreccicate.

Thanks!

**Comment by gorelikg** [comment]
Hi @avelinoferreira, 
All content associated with HTTP Status and Reason Code are documented in Chapter 3 of the Hardware Management Console Web Services API publication (http://www.ibm.com/servers/resourcelink).

Reason 4212 indicates that the:

```
The support element rejected communication from BCPii, likely for one of the
following reasons: the SEND BCPii permission was not granted to the LPAR
on this support element or the SE/HMC is missing the required MCL. Contact
your next level of support.
```

GDPS uses v1 flavor of BCPii (non HWIREST based) so if you're confident it's not a permission issue, i suspect that the system level is not recent enough. 

```
minimum IBM Z15 hardware level for:
- SE and HMC associated with the local and target CPC

mimimum BCPii microcode level applied to the corresponding SE and HMC:
- SE 2.15.0 with MCL P46598.370, Bundle S38
- HMC 2.15.0 with MCL P46686.001, Bundle H25
```

**Comment by avelinoferreira** [comment]
Thank you Galina for all detailed information! Have a nice week ahead!

Regards,

Avelino Ferreira
MVS system support - Certified IT Specialist - ITIL Certified
www.kyndryl.com<http://www.kyndryl.com/>
***@***.******@***.***>

In support of Delta
***@***.***

From: Galina Gorelik ***@***.***>
Sent: Tuesday, November 15, 2022 3:30 PM
To: IBM/zOS-BCPii ***@***.***>
Cc: Avelino Ferreira ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBM/zOS-BCPii] Error executing (Issue #22)

Hi @avelinoferreira, All content associated with HTTP Status and Reason Code are documented in Chapter 3 of the Hardware Management Console Web Services API publication (http: //www. ibm. com/servers/resourcelink). Reason 4212 indicates that the: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @avelinoferreira<https://github.com/avelinoferreira>,
All content associated with HTTP Status and Reason Code are documented in Chapter 3 of the Hardware Management Console Web Services API publication (http://www.ibm.com/servers/resourcelink<http://www.ibm.com/servers/resourcelink>).

Reason 4212 indicates that the:

The support element rejected communication from BCPii, likely for one of the

following reasons: the SEND BCPii permission was not granted to the LPAR

on this support element or the SE/HMC is missing the required MCL. Contact

your next level of support.

GDPS uses v1 flavor of BCPii (non HWIREST based) so if you're confident it's not a permission issue, i suspect that the system level is not recent enough.

minimum IBM Z15 hardware level for:

- SE and HMC associated with the local and target CPC



mimimum BCPii microcode level applied to the corresponding SE and HMC:

- SE 2.15.0 with MCL P46598.370, Bundle S38

- HMC 2.15.0 with MCL P46686.001, Bundle H25

**Comment by avelinoferreira** [comment]
Forgot to mention that I was issuing the rexx against an old CEC – EC12.

Thanks again!

Regards,

Avelino Ferreira
MVS system support - Certified IT Specialist - ITIL Certified
www.kyndryl.com<http://www.kyndryl.com/>
***@***.******@***.***>

In support of Delta
***@***.***

From: Avelino Ferreira
Sent: Wednesday, November 16, 2022 7:31 AM
To: IBM/zOS-BCPii ***@***.***>
Subject: RE: [EXTERNAL] Re: [IBM/zOS-BCPii] Error executing (Issue #22)

Thank you Galina for all detailed information! Have a nice week ahead!

Regards,

Avelino Ferreira
MVS system support - Certified IT Specialist - ITIL Certified
www.kyndryl.com<http://www.kyndryl.com/>
***@***.******@***.***>

In support of Delta
***@***.***

From: Galina Gorelik ***@***.******@***.***>>
Sent: Tuesday, November 15, 2022 3:30 PM
To: IBM/zOS-BCPii ***@***.******@***.***>>
Cc: Avelino Ferreira ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [IBM/zOS-BCPii] Error executing (Issue #22)

Hi @avelinoferreira, All content associated with HTTP Status and Reason Code are documented in Chapter 3 of the Hardware Management Console Web Services API publication (http: //www. ibm. com/servers/resourcelink). Reason 4212 indicates that the: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @avelinoferreira<https://github.com/avelinoferreira>,
All content associated with HTTP Status and Reason Code are documented in Chapter 3 of the Hardware Management Console Web Services API publication (http://www.ibm.com/servers/resourcelink<http://www.ibm.com/servers/resourcelink>).

Reason 4212 indicates that the:

The support element rejected communication from BCPii, likely for one of the

following reasons: the SEND BCPii permission was not granted to the LPAR

on this support element or the SE/HMC is missing the required MCL. Contact

your next level of support.

GDPS uses v1 flavor of BCPii (non HWIREST based) so if you're confident it's not a permission issue, i suspect that the system level is not recent enough.

minimum IBM Z15 hardware level for:

- SE and HMC associated with the local and target CPC



mimimum BCPii microcode level applied to the corresponding SE and HMC:

- SE 2.15.0 with MCL P46598.370, Bundle S38

- HMC 2.15.0 with MCL P46686.001, Bundle H25

**Comment by gorelikg** [comment]
very welcome and an older CEC would explain it :)
