### ISSUE TITLE
Sample for updating the defined capacity of an LPAR

### ISSUE THREAD

**Issue by FVANCOP** [IBM/zOS-BCPii#23]
Thanks for those samples who helped me a lot to retrieve LPAR/Images/CPC/etc... parameters.

I now want to update the Defined capacity of an LPAR through BCPII. I know how to do it with the previous BCPII method but do not find how to do it with this new way of working ? 

Can you provide a sample for it ?

Thanks,
François

**Comment by gorelikg** [comment]
Hi François,

If you look at the data model section under LPAR object, scroll a little bit, you'll see **defined-capacity** property. The qualifier column for the property has a **w** indicating you can update this property.  To update a property you would invoke the **Update Logical Partitions Properties REST API** (POST /api/logical-partitions/{logical-partition-id}) and pass in the **defined-capacity** and its new value in the corresponding Request body contents.

The code flow would be something like this (re-using existing logic in the RXQUERY1.rexx sample):
1. Use getLocalCPCInfo or GetCPCInfo to obtain the CPCuri  and the CPCTargetName of the CPC the lpar is on. (need as input for the next step - 2)
2. Use GetlocalLPARInfo or getLPARInfo to obtain the LPARuri and the LPARTargetName of the lpar you would like to update. (needed as input for the next step - 3)
3. issue the **Update Logical Partitions Properties REST API**:
``` drop userRequest.   (if using REXX)
       userRequest.httpmethod = HWI_REST_POST
       userRequest.uri = LparUri
       userRequest.requestbody = '{"defined-capacity":newValue}' 
                         <------ newValue is an integer representing the new value
       userRequest.targetname = LPARTargetName
       
       userRequest.encoding =
           1 (decimal)/HWI_ENCODING_UTF8(constant) for UTF-8
           2 (decimal)/HWI_ENCODING_IBM1047(constant) for
             IBM-1047
           Default, if initialized to 0, is IBM-1047.
           
        userRequest.REQUESTTIMEOUT =
             The 4 byte unsigned integer represents the time in
                milliseconds.
              • valid range is from 0 - 0x005265C0 (90 minutes)
           Default, if initialized to 0, is 60 minutes.
         
         Call HWIREST -> 
             Address BCPII "HWIREST userRequest. response."

         Handle response -> 
            - the HTTP status and reason codes section for this
               REST API indicates on success you should receive 204
            
            if RC = 0 & response.httpStatus = 204 Then
               say 'Successful update!'
            else
               call surfaceResponse RC, response.  
               (surfaceResponse routine in RXQUERY1.rexx)

```
Let me know if that makes sense.

**Comment by gorelikg** [comment]
As additional guidance for issuing a POST REST API, search for **DoPost:** in the [LPAR Load SYSREXX sample](https://github.com/IBM/zOS-BCPii/blob/main/Example-LPARLoad-SYSREXX/HWIXMRS3.rexx).

**Comment by FVANCOP** [comment]
I could successfully perform the operation.  Thanks a lot for your your explanations !
