### ISSUE TITLE
LPARs which can send BCPII commands

### ISSUE THREAD

**Issue by FVANCOP** [IBM/zOS-BCPii#24]
Hi,

Through the HMC console, in the security tab that can be found in the image profiles, we can specify if an LPAR can send BCPII command and/or can receive BCPII commands from other LPARs. If an LPAR can receive command, we have the choice to speficy that all LPARs can send commands to the LPAR associated to the profile or we can specify an explicit list of LPARs that can send BCPII commands to.

I do not find how to retrieve those informations through a BCPII program. At our site, because we are service provider with multiple customers, we have to specify explicit list of LPARs that can send commands. It would be usefull for us to be able to retrieve this information via a BCPII program.

Other question : is it possible to perform those definitions via BCPII or do we have to do it exclusively via the HMC console. It is a fastidious job (because we have lot of partitions and lot of customers....); would be interresting for us to do it via BCPII (Of course, the first LPAR has to be defined manually in the HMC console; but then, from this LPAR, we should be able to do the other definitions).

Thanks in advance,
François

**Comment by gorelikg** [comment]
Hi François,

Those operations are only possible via the HMC console. The closest thing (not exactly the same thing) that i can think of is retrieving a list of CPC's and LPARs. That list would include the CPC's and LPARs that are "accessible" via your application (thus the LPAR is allowed to send/receive BCPii commands). If this is an enhancement you think is valuable, would you mind opening an Idea for it?

IBM Ideas Portal -> https://www.ibm.com/support/pages/node/6438917

**Comment by FVANCOP** [comment]
Thanks for the answer. Unfortunately, I thought I would get this answer. 

I will post my idea, but I don't expect a lot from this action.

Thanks a lot,
Francois
